# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a38a3d5e3b0a8764743141e83650ec71c3b11392c43bffa10c87c76e3ce553fe2635566dbbee5763bd0026bc8cc69d191d0df53a45513a4a77d1c0305975c93

test:
  secret_key_base: 784d44b0df690061c97ccf7a924051067edd8a3630b29851b5a9b66d8065ee0d3c699e64741e42a8626500b6dc38b61e38f9608d2f210e7d3571e82b81bf4649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
